### ISSUE TITLE
Predefined system policy changed for CBR

### ISSUE THREAD

**Issue by marmulle2** [opentelekomcloud-docs/identity-access-management#29]
Predefined system policy changed for CBR service and 
CBR documentation is linked to https://docs.otc.t-systems.com/additional/permissions.html.
Old names were changed in [OTCPR-4452](https://jira.tsi-dev.otc-service.com/browse/OTCPR-4452)
and now names are following
![image](https://user-images.githubusercontent.com/122892537/218995922-79f3b955-d223-4da8-80c8-ca34c64d8ad7.png)

**Comment by vladimirhasko** [comment]
@lbelejka , @zokabai can you have a look?

**Comment by lbelejka** [comment]
Bug ticket has been created and reassigned to responsible person for that service
https://jira.tsi-dev.otc-service.com/browse/OTCSEC-4637

**Comment by lbelejka** [comment]
CBR system policy changes have been merged into gitea - The pull request has been merged as [254ba5a6c7](https://gitea.eco.tsi-dev.otc-service.com/docs/doc-exports/commit/254ba5a6c792ec498f22518355375bd43c32259f).

**Comment by lbelejka** [comment]
CBR system policy changes have been merged into gitea - The pull request has been merged as [254ba5a6c7](https://gitea.eco.tsi-dev.otc-service.com/docs/doc-exports/commit/254ba5a6c792ec498f22518355375bd43c32259f).

**Comment by lbelejka** [comment]
CBR system policy changes have been merged into gitea - The pull request has been merged as [254ba5a6c7](https://gitea.eco.tsi-dev.otc-service.com/docs/doc-exports/commit/254ba5a6c792ec498f22518355375bd43c32259f).
